version: "3.9"
services:
  springboot-app:
    container_name: springboot_sms
    build: .
    restart: always
    ports:
      - "9080:9080"
    networks:
      - springboot_sms-net
    environment:
      - spring.datasource.url:jdbc:mysql://mysqldb:3306/sms?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_PROFILES_ACTIVE:prod
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: mysql:8.1.0
    container_name: mysql_db_8.0_sms
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=sms
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - "3309:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - springboot_sms-net
networks:
  springboot_sms-net: